name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Set up Python 3.9 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run our unit tests
      - name: Run  tests
        run: |
          pytest -s
      # Deploy
      - name : Deploy Herocu
          - uses: actions/checkout@v2
          - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "github-login1"
            heroku_email: "kkamera317@gmail.com"
            usedocker: true
